-- generated by scripts/migrate_comp_leave_from_excel.py
-- workbook: 2026년 휴일근로 발생 및 사용 현황(목포운항관리센터).xlsm
-- config: comp_leave_excel_config.mokpo_2026.json
-- generated_at: 2026-06-24T08:47:01
begin;

insert into public.employees (name, office, status, retired_date)
values
  ('김형욱', '남강사무소', 'active', null),
  ('장인범', '남강사무소', 'retired', null),
  ('홍성욱', '남강사무소', 'active', null),
  ('김상초', '도초사무소', 'active', null),
  ('강인석', '목포센터', 'active', null),
  ('공석표', '목포센터', 'active', null),
  ('김미진', '목포센터', 'active', null),
  ('김주인', '목포센터', 'active', null),
  ('김진환', '목포센터', 'active', null),
  ('박상현', '목포센터', 'active', null),
  ('박수진', '목포센터', 'retired', null),
  ('서종성', '목포센터', 'active', null),
  ('손다윗', '목포센터', 'active', null),
  ('송의연', '목포센터', 'active', null),
  ('임현우', '목포센터', 'active', null),
  ('장수호', '목포센터', 'active', null),
  ('정병찬', '목포센터', 'active', null),
  ('정병희', '목포센터', 'active', null),
  ('정일영', '목포센터', 'active', null),
  ('정제상', '목포센터', 'active', null),
  ('정주용', '목포센터', 'active', null),
  ('정진일', '목포센터', 'active', null),
  ('정채석', '목포센터', 'active', null),
  ('진충열', '목포센터', 'active', null),
  ('한현규', '목포센터', 'retired', null),
  ('김종주', '북항사무소', 'active', null),
  ('김록주', '진도사무소', 'active', null),
  ('차문태', '진도사무소', 'active', null),
  ('김한주', '하의사무소', 'active', null)
on conflict (name, office) do update
set
  status = excluded.status,
  retired_date = excluded.retired_date;

insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 3
from public.employees
where name = '한현규' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 1
from public.employees
where name = '김미진' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4
from public.employees
where name = '정병희' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4.375
from public.employees
where name = '정제상' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4.125
from public.employees
where name = '장인범' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4
from public.employees
where name = '김형욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2025-12-25', '2025년 미사용분(성탄절)', 4
from public.employees
where name = '박상현' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4.375
from public.employees
where name = '정채석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '정병찬' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '서종성' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '정진일' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4.75
from public.employees
where name = '임현우' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4.125
from public.employees
where name = '김형욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '김록주' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-01-01', '신정', 4.167
from public.employees
where name = '김종주' and office = '북항사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4.375
from public.employees
where name = '정병희' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 3.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4.125
from public.employees
where name = '정진일' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '장수호' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '정주용' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4.75
from public.employees
where name = '정채석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4.125
from public.employees
where name = '장인범' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '김록주' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4
from public.employees
where name = '김한주' and office = '하의사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-16', '설날', 4.167
from public.employees
where name = '김종주' and office = '북항사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4.375
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4.25
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4.25
from public.employees
where name = '정주용' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4.125
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4
from public.employees
where name = '임현우' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4
from public.employees
where name = '정일영' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4
from public.employees
where name = '정제상' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4
from public.employees
where name = '정채석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4.75
from public.employees
where name = '김진환' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4.125
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4
from public.employees
where name = '장인범' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-17', '설날', 4
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4.375
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4.25
from public.employees
where name = '정주용' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4.125
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '정제상' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 9
from public.employees
where name = '임현우' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '정일영' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '정채석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '진충열' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '김진환' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4.75
from public.employees
where name = '서종성' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4.125
from public.employees
where name = '장인범' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '김형욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '박상현' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4
from public.employees
where name = '김한주' and office = '하의사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-02-18', '설날', 4.25
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4.375
from public.employees
where name = '임현우' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4.25
from public.employees
where name = '장수호' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4.25
from public.employees
where name = '정제상' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4
from public.employees
where name = '정병희' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4
from public.employees
where name = '정진일' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4.75
from public.employees
where name = '정채석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4.125
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4
from public.employees
where name = '김형욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4.25
from public.employees
where name = '김록주' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4
from public.employees
where name = '김한주' and office = '하의사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-01', '삼일절', 4
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4.375
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4.25
from public.employees
where name = '김종주' and office = '북항사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '임현우' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '장수호' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '정일영' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '정채석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4.75
from public.employees
where name = '정병찬' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4.125
from public.employees
where name = '김형욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4.25
from public.employees
where name = '김록주' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '박상현' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4
from public.employees
where name = '김한주' and office = '하의사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-03-02', '대체휴일', 4.25
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4.375
from public.employees
where name = '정병찬' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4.25
from public.employees
where name = '정진일' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '서종성' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '정병희' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '송의연' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '정일영' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '김진환' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '박수진' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 3
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '진충열' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4.75
from public.employees
where name = '장수호' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4.125
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4.25
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '정제상' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4
from public.employees
where name = '김한주' and office = '하의사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-01', '근로자의 날', 4.25
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4.375
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4.25
from public.employees
where name = '박상현' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4
from public.employees
where name = '정주용' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4
from public.employees
where name = '서종성' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4
from public.employees
where name = '정일영' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4
from public.employees
where name = '정병찬' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4.75
from public.employees
where name = '임현우' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4.125
from public.employees
where name = '김형욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4.25
from public.employees
where name = '김록주' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4
from public.employees
where name = '김한주' and office = '하의사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-05', '어린이날', 4.25
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4.5
from public.employees
where name = '박상현' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4.25
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4.25
from public.employees
where name = '정진일' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4
from public.employees
where name = '서종성' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4
from public.employees
where name = '정주용' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4
from public.employees
where name = '박수진' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4
from public.employees
where name = '장수호' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4.75
from public.employees
where name = '정병찬' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 3.125
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4.25
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-24', '부처님오신날', 4
from public.employees
where name = '정병희' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4.5
from public.employees
where name = '장수호' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4.25
from public.employees
where name = '박상현' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4
from public.employees
where name = '서종성' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4
from public.employees
where name = '정일영' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4
from public.employees
where name = '정주용' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4
from public.employees
where name = '진충열' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4
from public.employees
where name = '정병찬' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4.75
from public.employees
where name = '정채석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4.125
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4.25
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-05-25', '대체휴일', 4
from public.employees
where name = '김한주' and office = '하의사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4.375
from public.employees
where name = '정채석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4.25
from public.employees
where name = '서종성' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 3
from public.employees
where name = '정병찬' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4
from public.employees
where name = '송의연' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4
from public.employees
where name = '장수호' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4.75
from public.employees
where name = '손다윗' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4.125
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4
from public.employees
where name = '김주인' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4.25
from public.employees
where name = '임현우' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4
from public.employees
where name = '정제상' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4
from public.employees
where name = '김한주' and office = '하의사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-03', '지방선거', 4.25
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4.375
from public.employees
where name = '정주용' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4.25
from public.employees
where name = '박상현' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4.25
from public.employees
where name = '강인석' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4
from public.employees
where name = '정진일' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 3.5
from public.employees
where name = '차문태' and office = '진도사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4
from public.employees
where name = '박수진' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4
from public.employees
where name = '진충열' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4.75
from public.employees
where name = '서종성' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4.125
from public.employees
where name = '홍성욱' and office = '남강사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4
from public.employees
where name = '공석표' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4.25
from public.employees
where name = '정병희' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4
from public.employees
where name = '정제상' and office = '목포센터'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;
insert into public.comp_leave_earned (employee_id, holiday_date, holiday_name, earned_hours)
select id, '2026-06-06', '현충일', 4.25
from public.employees
where name = '김상초' and office = '도초사무소'
on conflict (employee_id, holiday_date, holiday_name) do update set earned_hours = excluded.earned_hours;

insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '김록주' and office = '진도사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 12.5, '기존 엑셀 이전 데이터'
from public.employees
where name = '김록주' and office = '진도사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 8.117, '기존 엑셀 이전 데이터'
from public.employees
where name = '김형욱' and office = '남강사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '김형욱' and office = '남강사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '김형욱' and office = '남강사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '김종주' and office = '북항사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '김종주' and office = '북항사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '김종주' and office = '북항사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '정병희' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-04-01', 3, '기존 엑셀 이전 데이터'
from public.employees
where name = '정병희' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '김진환' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 11, '기존 엑셀 이전 데이터'
from public.employees
where name = '김주인' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '김주인' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '임현우' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 10.5, '기존 엑셀 이전 데이터'
from public.employees
where name = '임현우' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-04-01', 3, '기존 엑셀 이전 데이터'
from public.employees
where name = '임현우' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '임현우' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 2, '기존 엑셀 이전 데이터'
from public.employees
where name = '정주용' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-04-01', 2.5, '기존 엑셀 이전 데이터'
from public.employees
where name = '정주용' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 13, '기존 엑셀 이전 데이터'
from public.employees
where name = '정주용' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 2, '기존 엑셀 이전 데이터'
from public.employees
where name = '정주용' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2025-12-25', 1, '기존 엑셀 이전 데이터'
from public.employees
where name = '김미진' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '차문태' and office = '진도사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '차문태' and office = '진도사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '차문태' and office = '진도사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '차문태' and office = '진도사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 16, '기존 엑셀 이전 데이터'
from public.employees
where name = '차문태' and office = '진도사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '손다윗' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '손다윗' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '손다윗' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 15.25, '기존 엑셀 이전 데이터'
from public.employees
where name = '손다윗' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '손다윗' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 3, '기존 엑셀 이전 데이터'
from public.employees
where name = '정진일' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 5.5, '기존 엑셀 이전 데이터'
from public.employees
where name = '정진일' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-04-01', 3.5, '기존 엑셀 이전 데이터'
from public.employees
where name = '정진일' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '서종성' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '서종성' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 1, '기존 엑셀 이전 데이터'
from public.employees
where name = '서종성' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 1, '기존 엑셀 이전 데이터'
from public.employees
where name = '정채석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 10.5, '기존 엑셀 이전 데이터'
from public.employees
where name = '정채석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '정채석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-04-01', 5, '기존 엑셀 이전 데이터'
from public.employees
where name = '정채석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 4.75, '기존 엑셀 이전 데이터'
from public.employees
where name = '정채석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 4.25, '기존 엑셀 이전 데이터'
from public.employees
where name = '정채석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '정병찬' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '정병찬' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 1, '기존 엑셀 이전 데이터'
from public.employees
where name = '정병찬' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '홍성욱' and office = '남강사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '홍성욱' and office = '남강사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '박상현' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 7, '기존 엑셀 이전 데이터'
from public.employees
where name = '박상현' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-04-01', 1, '기존 엑셀 이전 데이터'
from public.employees
where name = '박상현' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 13, '기존 엑셀 이전 데이터'
from public.employees
where name = '박상현' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '박상현' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '강인석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-04-01', 2, '기존 엑셀 이전 데이터'
from public.employees
where name = '강인석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '강인석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '강인석' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '김상초' and office = '도초사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 11.75, '기존 엑셀 이전 데이터'
from public.employees
where name = '김상초' and office = '도초사무소';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-01-01', 2, '기존 엑셀 이전 데이터'
from public.employees
where name = '정제상' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 9, '기존 엑셀 이전 데이터'
from public.employees
where name = '정제상' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 0.5, '기존 엑셀 이전 데이터'
from public.employees
where name = '정제상' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '정제상' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-02-01', 2, '기존 엑셀 이전 데이터'
from public.employees
where name = '진충열' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 2, '기존 엑셀 이전 데이터'
from public.employees
where name = '진충열' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-05-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '진충열' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-06-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '진충열' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-03-01', 4, '기존 엑셀 이전 데이터'
from public.employees
where name = '장수호' and office = '목포센터';
insert into public.comp_leave_usage (employee_id, used_date, used_hours, note)
select id, '2026-04-01', 8, '기존 엑셀 이전 데이터'
from public.employees
where name = '장수호' and office = '목포센터';

commit;

-- employees: 29
-- earned_rows: 185
-- usage_rows: 70